kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: s2i
  namespace: hamzahayd16-dev
spec:
  subdomain: s2i-spring
  to:
    kind: Service
    name: s2i
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge

